"""add animal types breeds animals and images tables

Revision ID: 1e408ce9e762
Revises: 63d32bf63383
Create Date: 2026-04-01 10:26:15.826651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e408ce9e762'
down_revision = '63d32bf63383'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal_types',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('breeds',
    sa.Column('animal_type_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['animal_type_id'], ['animal_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('animal_type_id', 'name', name='uq_breed_type_name')
    )
    with op.batch_alter_table('breeds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_breeds_animal_type_id'), ['animal_type_id'], unique=False)

    op.create_table('animals',
    sa.Column('farmer_id', sa.String(length=36), nullable=False),
    sa.Column('animal_type_id', sa.String(length=36), nullable=False),
    sa.Column('breed_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('age_months', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('available', 'reserved', 'sold', name='animal_status_enum'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['animal_type_id'], ['animal_types.id'], ),
    sa.ForeignKeyConstraint(['breed_id'], ['breeds.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_animals_animal_type_id'), ['animal_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_animals_breed_id'), ['breed_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_animals_farmer_id'), ['farmer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_animals_status'), ['status'], unique=False)

    op.create_table('animal_images',
    sa.Column('animal_id', sa.String(length=36), nullable=False),
    sa.Column('cloudinary_public_id', sa.String(length=500), nullable=False),
    sa.Column('cloudinary_url', sa.String(length=1000), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('animal_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_animal_images_animal_id'), ['animal_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_animal_images_animal_id'))

    op.drop_table('animal_images')
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_animals_status'))
        batch_op.drop_index(batch_op.f('ix_animals_farmer_id'))
        batch_op.drop_index(batch_op.f('ix_animals_breed_id'))
        batch_op.drop_index(batch_op.f('ix_animals_animal_type_id'))

    op.drop_table('animals')
    with op.batch_alter_table('breeds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_breeds_animal_type_id'))

    op.drop_table('breeds')
    op.drop_table('animal_types')
    # ### end Alembic commands ###
